<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Price Filter Slider</name>
   <tag></tag>
   <elementGuidId>5e33291a-0f73-4f73-9c39-040d18d28a05</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.mdc-slider__input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='range']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b0d9af39-90a5-41e3-92a3-08a32e5ed000</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>range</value>
      <webElementGuid>6dc41edd-282b-4841-b732-613a264140e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mdc-slider__input</value>
      <webElementGuid>684f1260-6b45-4f6c-a8c3-a5f294dea15d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-valuetext</name>
      <type>Main</type>
      <value>8k</value>
      <webElementGuid>484cc9f3-90e1-481a-9530-9ef061d712c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>35af2ad6-9de3-403e-9f97-7abfd958773f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>111</value>
      <webElementGuid>b28cd572-2a33-4c0e-ade1-f8e6e14ebaba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>8264</value>
      <webElementGuid>323a8278-0663-4ed9-94de-4759d72436e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;mat-typography&quot;]/app-root[1]/div[@class=&quot;container&quot;]/app-home[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;row no-gutters pt-3 ng-star-inserted&quot;]/div[@class=&quot;col-md-3 col-sm-12&quot;]/div[@class=&quot;filter-container&quot;]/app-price-filter[1]/mat-card[@class=&quot;mat-mdc-card mdc-card my-4 ng-star-inserted&quot;]/mat-card-content[@class=&quot;mat-mdc-card-content&quot;]/mat-slider[@class=&quot;mat-mdc-slider mdc-slider m-0 mat-primary mdc-slider--discrete&quot;]/input[@class=&quot;mdc-slider__input&quot;]</value>
      <webElementGuid>551f3681-40c9-4a10-b365-649c37ce27f3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='range']</value>
      <webElementGuid>63a2f796-852b-4d2a-8a40-63647bdbd037</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-slider/input</value>
      <webElementGuid>76584f4a-39cd-4abc-aa6d-fd5c380bf786</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'range']</value>
      <webElementGuid>18396f72-f9ac-4d91-b471-263b9ba92eea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
