<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mat-Error Password Format</name>
   <tag></tag>
   <elementGuidId>e515a4be-31ec-4478-8a1e-fc0ec35dc885</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mat-mdc-error-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//mat-error[@id='mat-mdc-error-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-error</value>
      <webElementGuid>6ba2494f-ec4d-4185-a17b-33976c0838e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-atomic</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3c8fec93-1a31-48f4-9ffc-354d154d3625</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-mdc-form-field-error mat-mdc-form-field-bottom-align ng-tns-c508571215-6 ng-star-inserted</value>
      <webElementGuid>d6fd1a3d-abb2-48b0-abca-dd541213ee5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-live</name>
      <type>Main</type>
      <value>polite</value>
      <webElementGuid>b9132b56-f160-4f8f-8c4f-522ca329b82a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-mdc-error-0</value>
      <webElementGuid>d7981574-23a5-45ea-ace1-e8c08ea91e28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Password should have minimum 8 characters, at least 1 uppercase letter, 1 lowercase letter and 1 number </value>
      <webElementGuid>1aa89805-b896-4b20-a9a3-4b59e191c881</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-mdc-error-0&quot;)</value>
      <webElementGuid>3cc42f34-6db7-4d75-8cd7-c072d79aabbd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//mat-error[@id='mat-mdc-error-0']</value>
      <webElementGuid>10caa5f2-07ec-4d46-86d1-9da16e130075</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/following::mat-error[1]</value>
      <webElementGuid>ca4bb086-f3ca-43b4-a763-2ebee69ef990</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User name'])[1]/following::mat-error[1]</value>
      <webElementGuid>e480bbe5-75d4-4360-97d5-de72ef9a211b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirm Password'])[1]/preceding::mat-error[1]</value>
      <webElementGuid>4ab2b7b0-cfd1-4499-8aeb-bd2e75eaaa6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gender:'])[1]/preceding::mat-error[1]</value>
      <webElementGuid>06d35685-1d60-44f7-acb1-b82f49f0d705</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Password should have minimum 8 characters, at least 1 uppercase letter, 1 lowercase letter and 1 number']/parent::*</value>
      <webElementGuid>017a92eb-4739-453f-ad8f-87ea254e71f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-error</value>
      <webElementGuid>b63bb824-776b-499c-bd0f-bf133d88889f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-error[@id = 'mat-mdc-error-0' and (text() = ' Password should have minimum 8 characters, at least 1 uppercase letter, 1 lowercase letter and 1 number ' or . = ' Password should have minimum 8 characters, at least 1 uppercase letter, 1 lowercase letter and 1 number ')]</value>
      <webElementGuid>0129dd82-69d5-49b1-bc1d-ae66f6189812</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
